# PTP Tunnel Module - USB remote access layer
MODULE_NAME = ptptun
MODULE_OBJS = $(BUILD_DIR)/ptptun.o

TOP_DIR = ../..
include $(TOP_DIR)/modules/Makefile

.DEFAULT_GOAL := $(BUILD_DIR)/module_complete
