# WiFi Enable Module - Canon 70D WiFi Init + Server
MODULE_NAME = wifi_enable
MODULE_OBJS = $(BUILD_DIR)/wifi_enable.o

TOP_DIR = ../..
include $(TOP_DIR)/modules/Makefile

.DEFAULT_GOAL := $(BUILD_DIR)/module_complete
